# Generated by Django 2.1.5 on 2023-06-07 04:46

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('product_img', models.ImageField(upload_to='product_img')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_Delete', models.BooleanField(default=False)),
                ('product_click', models.IntegerField(default=0)),
                ('product_unit', models.CharField(max_length=20)),
                ('product_abstract', models.CharField(max_length=120)),
                ('product_content', tinymce.models.HTMLField()),
                ('product_type', models.IntegerField(choices=[(1, '书籍'), (2, '交通工具'), (3, '电子设备'), (4, '电子外设'), (5, '本地拍品'), (6, '其他')])),
            ],
        ),
    ]
