# Generated by Django 3.2.19 on 2023-06-09 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productinfo_product_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinfo',
            name='product_unit',
        ),
    ]
