# Generated by Django 2.1.5 on 2023-06-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_productinfo_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='product_img',
            field=models.ImageField(blank=True, null=True, upload_to='static/product_img/', verbose_name='商品图片'),
        ),
    ]
