# Generated by Django 2.1.5 on 2023-06-07 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auctions', '0001_initial'),
        ('user_part', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('order_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('order_status', models.IntegerField(choices=[(0, '未付款'), (1, '已付款'), (2, '已发货'), (3, '已结束')], default=0)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.AuctionInfo')),
                ('order_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_part.UserInfo')),
            ],
        ),
    ]
