# Generated by Django 2.0.4 on 2023-05-12 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='order_pro',
            new_name='order_pro_id',
        ),
    ]
