# Generated by Django 2.1.5 on 2023-06-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_part', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='deposit_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
