# Generated by Django 2.1.5 on 2023-06-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_part', '0002_auto_20230608_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='deposit_balance',
            field=models.IntegerField(default=0),
        ),
    ]
