# Generated by Django 3.2.19 on 2023-06-09 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_part', '0004_alter_userinfo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users', verbose_name='用户头像'),
        ),
    ]
