# Generated by Django 3.2.19 on 2023-06-09 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_part', '0005_userinfo_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='avatar',
        ),
    ]
