# Generated by Django 3.2.19 on 2023-06-09 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_part', '0004_alter_userinfo_id'),
        ('products', '0002_alter_productinfo_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_part.userinfo')),
            ],
        ),
    ]
