# Generated by Django 3.2.19 on 2023-06-09 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartinfo',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cartinfo',
            name='user',
        ),
    ]
